FROM php:8.3-fpm

RUN apt-get update && apt-get install -y \
    git unzip libicu-dev libzip-dev zip

RUN docker-php-ext-install intl pdo pdo_mysql

RUN docker-php-ext-install opcache

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY docker/backend/opcache.ini /usr/local/etc/php/conf.d/z-opcache.ini

COPY docker/backend/www.conf /usr/local/etc/php-fpm.d/www.conf

WORKDIR /var/www