services:
  proxy:
    image: nginx:1.24
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./backend/app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - api-network

  backend:
    container_name: symfony_api
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    working_dir: /var/www
    volumes:
      - ./backend/app:/var/www
    networks:
      - api-network

  db:
    image: mariadb:11.4
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: intelia
      MARIADB_USER: intelia
      MARIADB_PASSWORD: intelia
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - api-network
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - api-network
volumes:
  database_data: 
networks:
  api-network:



